baseurl = "https://example.org"
languageCode = "fa-ir"
title = "قم لاگ"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:filename/"
    page = "/:filename/"

[[menu.main]]
    name = "درباره ما"
    url = "/about/"
[[menu.main]]
    name = "تلگرام"
    url = "https://t.me/qomlug"
[[menu.main]]
    name = "جلسات"
    url = "/meetting/"

[params]
    description = ""

    [params.logo]
    url = "logo.jpg"
    width = 50
    height = 50
    alt = "Logo"

